### ISSUE TITLE
Values and section with the same name are ignored

### ISSUE THREAD

**Issue by mwm** [magthe/hsini#16]
The interpretation of multiple sections (or values in a section) with the same name varies between implementations. In particular, according to wikipedia,

> Some programs use duplicate property names to implement multi-valued properties.

and

> Interpretation of multiple section declarations with the same name also varies

Since I don't see an "upload file" option, I'll paste a sample in a second comment.

Note that it uses multiple values with the same name (_Toggle_) in the gui-128x64 section to create multiple, different toggles in the gui.

It also uses multiple sections with the same name (_mixer_) to create multiple mixers with different values. In this case, **order matters**, as mixers are applied to the output of the previous mixer. Further, for human editing, the order of channels & mixers matter, as the mixers generate output for the channel that they follow. While this doesn't matter to the program, it does to human editors of the file.

**Comment by mwm** [comment]
name=Phoenix
mixermode=Advanced
icon=CHAMP.BMP
[radio]
protocol=PPM
num_channels=6
fixed_id=123456
tx_power=150mW

[protocol_opts]
Center PW=1100
Delta PW=400
Notch PW=400
Frame Size=22500

[channel1]
template=expo_dr
[mixer]
src=AIL
dest=Ch1
[mixer]
src=AIL
dest=Ch1
switch=AIL DR1
scalar=70

[channel2]
template=expo_dr
[mixer]
src=ELE
dest=Ch2
[mixer]
src=ELE
dest=Ch2
switch=AIL DR1
scalar=70

[channel3]
safetysw=Virt1
safetyval=-100
template=expo_dr
[mixer]
src=THR
dest=Ch3
[mixer]
src=THR
dest=Ch3
switch=!FMODE0
curvetype=fixed
[mixer]
src=THR
dest=Ch3
switch=ELE DR1

[channel4]
template=expo_dr
[mixer]
src=RUD
dest=Ch4
[mixer]
src=RUD
dest=Ch4
switch=AIL DR1
scalar=70

[channel5]
template=complex
[mixer]
src=AUX4
dest=Ch5
scalar=0
usetrim=0
curvetype=fixed
[mixer]
src=MIX2
dest=Ch5
switch=!MIX1
usetrim=0
curvetype=min/max
points=0
[mixer]
src=GEAR1
dest=Ch5
switch=ELE DR1
curvetype=min/max
points=0

[channel6]
template=complex
[mixer]
src=THR
dest=Ch6
switch=FMODE0
scalar=-100
usetrim=0
curvetype=fixed
[mixer]
src=THR
dest=Ch6
switch=FMODE1
scalar=0
usetrim=0
curvetype=fixed
[mixer]
src=FMODE0
dest=Ch6
switch=FMODE2
usetrim=0
curvetype=fixed
[mixer]
src=Virt3
dest=Ch6
switch=ELE DR0
usetrim=0

[channel7]
template=simple
[mixer]
src=AUX4
dest=Ch7

[channel8]
template=complex
[mixer]
src=AUX5
dest=Ch8
usetrim=0
[mixer]
src=MIX2
dest=Ch8
switch=!MIX1
usetrim=0
curvetype=min/max
points=0
[mixer]
src=AUX5
dest=Ch8
switch=ELE DR0

[channel9]
template=expo_dr
[mixer]
src=ELE
dest=Ch9
curvetype=expo
points=35,35
[mixer]
src=ELE
dest=Ch9
switch=AIL DR1
scalar=70

[virtchan1]
template=complex
[mixer]
src=Virt1
dest=Virt1
usetrim=0
curvetype=min/max
points=0
[mixer]
src=Ch3
dest=Virt1
offset=-1
usetrim=0
muxtype=add
[mixer]
src=AIL
dest=Virt1
switch=RUD DR1
usetrim=0
curvetype=fixed

[virtchan3]
name=Pitch
template=complex
[mixer]
src=THR
dest=Virt3
scalar=55
offset=45
usetrim=0
[mixer]
src=THR
dest=Virt3
switch=FMODE2
usetrim=0

[trim1]
src=LEFT_V
pos=TRIMLV+
neg=TRIMLV-
[trim2]
src=RIGHT_V
pos=TRIMRV+
neg=TRIMRV-
[trim3]
src=LEFT_H
pos=TRIMLH+
neg=TRIMLH-
[trim4]
src=RIGHT_H
pos=TRIMRH+
neg=TRIMRH-
value=1,0,0
[trim5]
src=AUX4
pos=TRIM_L-
neg=TRIM_L+
[trim6]
src=AUX5
pos=TRIM_R-
neg=TRIM_R+
[timer2]
type=permanent
val=900
[datalog]
switch=None
rate=1 sec
[safety]
Auto=min
[gui-128x64]
V-trim=59,10,1
H-trim=5,59,3
V-trim=65,10,2
H-trim=74,59,4
Small-box=2,22,Ch3
Small-box=2,31,Timer1
Small-box=2,40,Timer2
Model=75,20
Battery=102,1
Toggle=4,10,0,72,0,Virt1
Toggle=13,10,0,67,0,ELE DR
Toggle=22,10,0,69,0,AIL DR
Toggle=31,10,1,134,194,FMODE
Toggle=40,10,0,71,0,GEAR
TxPower=102,7
quickpage1=Channel monitor

**Comment by magthe** [comment]
I'm not sure I understand what behaviour you would like to see.

As you point out interpretation differs between implementations, and _hsini_ does have an interpretation.

Am I right in thinking you would like 

1. values of duplicate properties to be collected in a list, and
2. multiple sections with the same name are merged?

I'll close this ticket as it's very old now (my fault for not paying attention to _hsini_ for so long). If this still matters to you then feel free to re-open it, and maybe provide a smaller example with an explanation of what result you'd like.
