### ISSUE TITLE
Release the version for GHC 8.0.1 on Hackage 

### ISSUE THREAD

**Issue by Mikolaj** [magthe/hsini#18]
Hi! I've verified it works fine with GHC 8.0.1. Could you release it on Hackage? Or I may do that for you, if you lack time ATM. Thank you!

**Comment by Mikolaj** [comment]
Or just give me access to the Hackage project and I may alternatively tweak the bounds in the .cabal file of the last released version. I'd really appreciate it, since it would greatly simplify testing on Travis a potential GHC 8.0.1 bug I've found.

**Comment by magthe** [comment]
Hope that helps.

**Comment by Mikolaj** [comment]
A lot. :) Thank you.
