### ISSUE TITLE
Submit the package to Stackage

### ISSUE THREAD

**Issue by Mikolaj** [magthe/hsini#21]
Now that you have working stack.yaml files, it shouldn't be too hard to submit the package to  

https://github.com/fpco/stackage

I'd do it myself, but I _think_ they require maintainers to do that. Thanks!

**Comment by Mikolaj** [comment]
Here are some helpful instructions. :) 

https://www.stackage.org/package/hsini

**Comment by Mikolaj** [comment]
If you prefer, I can add hsini to stackage under my name. But then I'd need write access to the repo to be able to fix any issue that stackage alerts me to. I can (co-) maintain the Hackage package, if you'd like.

**Comment by magthe** [comment]
See commercialhaskell/stackage#3705.

**Comment by Mikolaj** [comment]
Splendid, it works!
